/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package santosh;

/**
 *
 * @author ravish
 */
public class pramod extends javax.swing.JFrame {

    /**
     * Creates new form pramod
     */
    public pramod() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        chrome = new javax.swing.JRadioButton();
        IE = new javax.swing.JRadioButton();
        chromeItems = new javax.swing.JComboBox();
        IEItems = new javax.swing.JComboBox();
        program1 = new javax.swing.JCheckBox();
        program2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(chrome);
        chrome.setSelected(true);
        chrome.setText("Chrome");
        chrome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chromeActionPerformed(evt);
            }
        });
        getContentPane().add(chrome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        buttonGroup1.add(IE);
        IE.setText("IE Browser");
        IE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IEActionPerformed(evt);
            }
        });
        getContentPane().add(IE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        chromeItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(chromeItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        IEItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(IEItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        program1.setText("Program1");
        getContentPane().add(program1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        program2.setText("program2");
        getContentPane().add(program2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(program1.isSelected()){
            
            Santosh s=new Santosh();
            s.getName();
        }
        
        if(program2.isSelected()){
            new tableData().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chromeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chromeActionPerformed
        // TODO add your handling code here:
        if(chrome.isSelected()){
            chromeItems.enable();
            
            IEItems.disable();
        }
    }//GEN-LAST:event_chromeActionPerformed

    private void IEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IEActionPerformed
        // TODO add your handling code here:
        if(IE.isSelected()){
            chromeItems.disable();
            IEItems.enable();
        }
    }//GEN-LAST:event_IEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pramod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pramod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pramod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pramod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pramod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton IE;
    private javax.swing.JComboBox IEItems;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton chrome;
    private javax.swing.JComboBox chromeItems;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox program1;
    private javax.swing.JCheckBox program2;
    // End of variables declaration//GEN-END:variables
}
